language: c
os: linux
dist: focal

jobs:
  include:
  - name: z/Arch
    if: branch != master OR type == pull_request
    arch: s390x
    compiler:
    - gcc
    env:
    - CC="gcc"
    - CXX="g++"
    - CFLAGS="-march=native -mzvector -Wextra -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    - CXXFLAGS="-march=native -mzvector -Wextra -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    addons:
      apt:
        packages: ninja-build python3-pip gcc g++

  - name: POWER9
    if: branch != master OR type == pull_request
    arch: ppc64le
    compiler:
    - clang
    env:
    - CC="clang"
    - CXX="clang++"
    - CFLAGS="-mcpu=power9 -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    - CXXFLAGS="-mcpu=power9 -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    addons:
      apt:
        packages: ninja-build python3-pip clang

  - name: POWER8
    if: branch != master OR type == pull_request
    arch: ppc64le
    compiler:
    - clang
    env:
    - CC="clang"
    - CXX="clang++"
    - CFLAGS="-mcpu=power8 -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    - CXXFLAGS="-mcpu=power8 -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    addons:
      apt:
        packages: ninja-build python3-pip clang

  - name: POWER7
    if: branch != master OR type == pull_request
    arch: ppc64le
    compiler:
    - clang
    env:
    - CC="clang"
    - CXX="clang++"
    - CFLAGS="-mcpu=power7 -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    - CXXFLAGS="-mcpu=power7 -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    addons:
      apt:
        packages: ninja-build python3-pip clang

  - name: POWER6
    if: branch != master OR type == pull_request
    arch: ppc64le
    compiler:
    - clang
    env:
    - CC="clang"
    - CXX="clang++"
    - CFLAGS="-mcpu=power6 -maltivec -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    - CXXFLAGS="-mcpu=power6 -maltivec -Weverything -Werror -DSIMDE_CONSTRAINED_COMPILATION"
    addons:
      apt:
        packages: ninja-build python3-pip clang

before_install:
- cat /proc/cpuinfo
- cat /proc/meminfo

install:
- pip3 install meson

script:
- meson setup build -Db_coverage=true
- ninja -C build -v -j 6
- meson test -C build --print-errorlogs

notifications:
  email: false
